### ISSUE TITLE
Readme is outdated

### ISSUE THREAD

**Issue by 12people** [taljacobson/flutter_mailer#11]
It seems that this works on iOS (right?) and the current version is much later than the recommended 3.0.0. Please mention this in the Readme.

**Comment by taljacobson** [comment]
### yes it works on ios. 

i only know a smidge of objc or native ios in particular. 
and so some of the ios features are mission.
a cool feature in perticular that exists in the React native module that this plugin is based off, is returning if the email was sent, cancelled, or draft. and returning the promise when it does..
on android that is not possible and a empty response is returned right away.

**Comment by taljacobson** [comment]
as with the recommanded version the pub badge is always the best bet for the latest version.
but read me updated
