### ISSUE TITLE
Android: return succes onActivityForResult instead of after starting the intent.

### ISSUE THREAD

**Issue by robindijkhof** [taljacobson/flutter_mailer#16]
The send method should return success onActivityForResult. Currently it returns success after starting the intent. This gives the illusion the user is done sending. However, the user can still be in for example Gmail, or even has to pick an app to send the mail with.

**Comment by taljacobson** [comment]
A PR is most welcome.

**Comment by taljacobson** [comment]
thank you for the PR.
i was only able to test it today. sorry for the delay.
looks good to me.
