### ISSUE TITLE
PlatformException when using Fluttermailer.send(...) after flutter upgrade from 1.9 to 1.12

### ISSUE THREAD

**Issue by sceee** [taljacobson/flutter_mailer#19]
Unfortunately, I guess since the update to flutter 1.12.13+hotfix.5, the following `PlatformException` raises at the `FlutterMailer.send(mailOptions)` call:
```
PlatformException (PlatformException(error, Attempt to invoke virtual method 'void android.app.Activity.startActivityForResult(android.content.Intent, int)' on a null object reference, null))
```

The complete stack is the following:
```
E/flutter ( 6682): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'void android.app.Activity.startActivityForResult(android.content.Intent, int)' on a null object reference, null)
E/flutter ( 6682): #0      StandardMethodCodec.decodeEnvelope 
package:flutter/…/services/message_codecs.dart:569
E/flutter ( 6682): #1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:321
E/flutter ( 6682): <asynchronous suspension>
E/flutter ( 6682): #2      FlutterMailer.send 
package:flutter_mailer/flutter_mailer.dart:9
E/flutter ( 6682): #3      Mailer.emailIt.<anonymous closure> 
package:my_app/services/mailer.dart:67
E/flutter ( 6682): <asynchronous suspension>
E/flutter ( 6682): #4      _rootRunUnary  (dart:async/zone.dart:1134:38)
E/flutter ( 6682): #5      _CustomZone.runUnary  (dart:async/zone.dart:1031:19)
E/flutter ( 6682): #6      _FutureListener.handleValue  (dart:async/future_impl.dart:139:18)
E/flutter ( 6682): #7      Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:680:45)
E/flutter ( 6682): #8      Future._propagateToListeners  (dart:async/future_impl.dart:709:32)
E/flutter ( 6682): #9      Future._completeWithValue  (dart:async/future_impl.dart:524:5)
E/flutter ( 6682): #10     Future._asyncComplete.<anonymous closure>  (dart:async/future_impl.dart:554:7)
E/flutter ( 6682): #11     _rootRun  (dart:async/zone.dart:1126:13)
E/flutter ( 6682): #12     _CustomZone.run  (dart:async/zone.dart:1023:19)
E/flutter ( 6682): #13     _CustomZone.runGuarded  (dart:async/zone.dart:925:7)
E/flutter ( 6682): #14     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:965:23)
E/flutter ( 6682): #15     _microtaskLoop  (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 6682): #16     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:52:5)
```

The versions I am using are:
* Flutter v1.12.13+hotfix.5
* flutter_mailer 0.4.2

Unfortunately I have no idea what broke here and how to solve it. I did not change application code and prior to the flutter update, it worked. Do you have any idea?

**Comment by taljacobson** [comment]
does going down to `flutter_mailer 0.4.1` help?

**Comment by sceee** [comment]
@taljacobson unfortunately not, the error also occurs with `flutter_mailer 0.4.1`.

**Comment by sceee** [comment]
@taljacobson sorry, please forget what I wrote in my previous comment, I made an error when locking it to `0.4.1`.
So after correctly locking to `0.4.1`, it works again.

**Comment by taljacobson** [comment]
@robindijkhof do you know what might be the problem?

**Comment by robindijkhof** [comment]
I'd guess the activy is null. Not sure why though. As of 1.12 there is an new api. See https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration The old api should not break, but maybe there's a bug?

Unfortunately my setup broke, so I can't look into it.

**Comment by robindijkhof** [comment]
Just tried to reproduce it, but I couldn't. Adding a null check would work for sure, though I wouldn't know what to do when it is null.

**Comment by taljacobson** [comment]
flutter was updated to 1.17 and the plugin latest is now 0.5.0. since this issue seems stale i will close it for the time being.

please update to the latest and migrate your flutter android based off of the migrating path 
[Upgrading-pre-1.12-Android-projects]( https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)
