### ISSUE TITLE
migrate to new platform API 

### ISSUE THREAD

**Issue by taljacobson** [taljacobson/flutter_mailer#20]
flutter 1.12 introduced a new platform API for Android and IOS plugins and while the old API that is being used will still work for the foreseeable future we should migrate to it.

https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

while i believe i can migrate the java/Android code,
i will need help with the IOS code, since i am not a objective C or swift programmer. and not very familiar with the IOS native environment.

https://github.com/taljacobson/flutter_mailer/issues/19#issuecomment-573319902

**Comment by cmcoffee91** [comment]
I'll help with iOS if no one else has yet.

**Comment by taljacobson** [comment]
@cmcoffee91 sorry if i didn't respond. ios does need some work on, but it is not something that has to do with migration, since the migration is android specific. 

with that in mind if you or any one else cares to clean it up, migrate to swift or enhance response to return if its `sent|draft|canceled`. which in ios is possible.

help would be much appreciated.
