### ISSUE TITLE
Attachment path get mangled.

### ISSUE THREAD

**Issue by chrislaurie-bs** [taljacobson/flutter_mailer#22]
My storage class returns a path to my file as:

/data/user/0/...

Which I pass directly in the attachments property.

The mail fails with this error:

PlatformException(error, Failed to find configured root that contains /data/data/...

Samsung Galaxy S7

**Comment by taljacobson** [comment]
you might want to check out [path_provider](https://pub.dev/packages/path_provider). 

the example app has usage for using it for creating a local file https://github.com/taljacobson/flutter_mailer/blob/master/example/lib/main.dart#L225

issue #10 has some examples of how it might work.

**Comment by taljacobson** [comment]
closing in favor of #10. since it seems like a problem of android configuration and attachment path.
