### ISSUE TITLE
For iOS, don't return the feedback MFMailComposeResult result 

### ISSUE THREAD

**Issue by herveperoteau** [taljacobson/flutter_mailer#31]
Hi,

For iOS, in the MFMailComposeViewControllerDelegate, you don't return the feedback MFMailComposeResult result.
It could be easily by keep the result:(FlutterResult)result in a variable and call it in the MFMailComposeViewControllerDelegate method.

**Comment by taljacobson** [comment]
yes there is a pending PR #28 i made to return the result.

i have not been able to properly test it though due to issues with my physical device, i did make it available on pub with a dev version  of 0.6.0-dev.1.

hopefully i will be able to test and merge it soon.

**Comment by herveperoteau** [comment]
Ok I could test it on device

What is the correct syntax to use in my yaml to use your branch ?

#  flutter_mailer: ^0.4.1+1
  flutter_mailer:
    https://github.com/taljacobson/flutter_mailer/tree/MailerResponse

**Comment by herveperoteau** [comment]
Missing } in your branch

**Comment by herveperoteau** [comment]
After the fix of missing } it’s works as expected on iOS device. (See my screenshot)

Did you know when you could published it ? Because I need this feature quickly.
Please give me a feedback 

Thanks
Hervé

**Comment by taljacobson** [comment]
ok published a new dev version 0.6.0-dev.2, please try it out,

**Comment by herveperoteau** [comment]
It works well
Thanks
