### ISSUE TITLE
MissingPluginException(No implementation found for method send on channel flutter_mailer)

### ISSUE THREAD

**Issue by fatahzull** [taljacobson/flutter_mailer#37]
Hi, I got this exception 
`MissingPluginException(No implementation found for method send on channel flutter_mailer)`

appreciate if you could assist me. Thanks

**Comment by taljacobson** [comment]
Please provide more information, such as the out put of ’flutter doctor’, which platform the error occurs on.

**Comment by madd-project** [comment]
Hey Brother @fatahzull , 
How are You? 
I wanted to provide you the solution, 

If you try Re-installing the App or Re-running it, (except HotReload) you will see the results.
For me I was having the same Trouble, but after  rerunning it, it is just gone and i am free..

Have  a Look, If i were to know about the package before, I would be telling you the answer ahead, but yeah, for future someone may benefit this answer. 

❤️
