### ISSUE TITLE
How to Use Custom HTML with flutter_mailer

### ISSUE THREAD

**Issue by madd-project** [taljacobson/flutter_mailer#41]

**Comment by taljacobson** [comment]
Not sure what you mean by custom html.

You can insert html to the body with combination of the html flag.

Although it is dependent on the OS, and receiving email client app. 
On iOS html works good, the default iOS mail app will render inline images, h1-6, and common html element, styling mostly works with inline attributes.
On the other hand android is more complicated, it is very much dependent on the app receiving the intent.
I have not found an app on Android which will display an inline image.
Gmail basically only respects the line break tag as of the last few years, used to respect h1-6, strong, I, and some others.

**Comment by madd-project** [comment]
Oh Ok, So there is not option we can use 
```
<html>
....
<body>
<img src ...>
</body>
</html>
.....
```

with the GMAIL..

**Comment by madd-project** [comment]
Because i Did it, But it didnot worked for me.
No Issues This Package is really made with ❤️ , I installed the Package not for HTML, but just for Sending Gmails. and it is really helping, I am not able to draft more respect and Love, because i have already crossed the Limits, You are really awesome to think about the Opensource,

Using HTML was my Secondary Option. Though we can Enhance it..
