### ISSUE TITLE
Note: /Users/administrator/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_mailer-2.0.0/android/src/main/java/com/dataxad/flutter_mailer/FlutterMailerPlugin.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by Development4A** [taljacobson/flutter_mailer#43]
error message on "flutter build appbundle"

Because http >=0.13.0 depends on http_parser ^4.0.0 and firebase_auth_web <0.4.0-1.0.nullsafety.0 depends on http_parser ^3.1.3, http >=0.13.0 is incompatible with firebase_auth_web <0.4.0-1.0.nullsafety.0.
And because firebase_auth >=0.15.2 <0.17.0-dev.1 depends on firebase_auth_web ^0.1.1, http >=0.13.0 is incompatible with firebase_auth >=0.15.2 <0.17.0-dev.1.
So, because easy_list_pro depends on both http ^0.13.0 and firebase_auth ^0.15.3, version solving failed.

**Comment by taljacobson** [comment]
Seems like it a dependency issue with http ^0.13.0 and firebase_auth ^0.15.3 requiring Different major versions of http_parser.

Try to update those packages.

As with the android deprecated APIs, it should still compile.

**Comment by Development4A** [comment]
Updated the two and got a different error for firebase_core.

Did:
dependency:
  firebase_core: ^1.5.0
dependency_overrides:
  firebase_core: ^0.4.0

Took the above out and I get:
Note: /Users/administrator/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_mailer-2.0.0/android/src/main/java/com/dataxad/flutter_mailer/FlutterMailerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:validateSigningRelease'.                
> Keystore file not set for signing config release                      
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 48s                                                     
Running Gradle task 'bundleRelease'...                                  
Running Gradle task 'bundleRelease'... Done                        49.0s
Gradle task bundleRelease failed with exit code 1
administrator@iMac easy_list_pro % flutter build appbundle Xlint:deprecation
Target file "Xlint:deprecation" not found.
administrator@iMac easy_list_pro % flutter build appbundle -Xlint:deprecation
Could not find an option with short name "-X".

The ios version is in the App store.
I do not know what I am doing.

**Comment by Development4A** [comment]
Tried to build as an APK instead of APPBUNDLE. the Java message warning disappears but the "app:validateSigningRelease" is still there so it will not build.

**Comment by taljacobson** [comment]
seems to be a android signing issue.

is this the first time building for release?



try following this https://flutter.dev/docs/deployment/android#signing-the-app

**Comment by Development4A** [comment]
I have another Flutter App that I had no problem with compiling and send to the Play Store.

**Comment by Development4A** [comment]
I found the problem. I misspelled key.properties.

Sorry about taking up so much space.
