### ISSUE TITLE
Inappropriate versioning after updating minSdkVersion to 21

### ISSUE THREAD

**Issue by calcitem** [taljacobson/flutter_mailer#55]
Hello,

I noticed that the minSdkVersion was updated to 21 in commit [9e691e44a8c75f0e0edb06560420ec262142563b](https://github.com/taljacobson/flutter_mailer/commit/9e691e44a8c75f0e0edb06560420ec262142563b). However, the version number was only updated in the PATCH segment, which could cause build failures for projects that depend on flutter_mailer or packages that transitively depend on it, such as [catcher](https://github.com/jhomlala/catcher/blob/master/pubspec.yaml#L22C1-L22C25).

According to [Semantic Versioning](https://semver.org/), when making a change that introduces potential compatibility issues, the MINOR version number should be increased to reflect the introduction of new features or requirements, such as a higher minSdkVersion.

I kindly suggest the following actions to resolve this issue:

1. Update the version number of flutter_mailer to increase the MINOR version segment (e.g., from 2.0.x to 2.1.0) to reflect the change in minSdkVersion.
2. Publish the updated version to [pub.dev](https://pub.dev/), so that dependent packages can specify the appropriate version range in their pubspec.yaml files.

This will help to prevent build failures for projects that are not yet ready to update their minSdkVersion to 21, as they can continue to use the previous compatible version of flutter_mailer.

Additionally, it might be helpful to consider reverting the incorrect v2.0.3 version and taking the following steps:

1. Mark v2.0.3 as deprecated on pub.dev, signaling to other developers not to use this version and to opt for other available versions.
2. After reverting, release a new PATCH version (e.g., v2.0.4) with the previous minSdkVersion to maintain compatibility with existing Flutter projects.
3. Then, release a new MINOR version (e.g., v2.1.0) with the updated minSdkVersion of 21 to signify the different compatibility requirements.

This way, projects depending on flutter_mailer or those that transitively depend on it can choose the appropriate version based on their specific needs.

Thank you for your attention to this matter, and for your work on the flutter_mailer package.

Best regards,
Calcitem

**Comment by taljacobson** [comment]
reverted 2.0.3 with 2.0.4 and re published 2.0.3 as 2.1.0

**Comment by calcitem** [comment]
Dear flutter_mailer maintainer,

I hope this message finds you well.

Firstly, I would like to express my sincere appreciation for your quick and helpful response to my previous request regarding the versioning issue in flutter_mailer. Your proactive actions in reverting v2.0.3, creating v2.0.4, and releasing v2.1.0 to handle the non-backward compatible changes are highly commendable.

However, I regret to inform you that the recent changes have not fully resolved the issues for my project. Despite your efforts, my application is still failing to build. This is because my app indirectly depends on flutter_mailer through a chain of dependencies, which prevents me from resolving this issue by adjusting the version range in my app's dependencies.

Upon further review of Semantic Versioning, I realize I may have provided you with incorrect advice previously. Indeed, a MINOR version update implies backward-compatible functionality additions, and a PATCH version update implies backward-compatible bug fixes. However, changing the minSdkVersion may indeed be considered a breaking change that requires a MAJOR version update.

With that in mind, I humbly suggest the following steps:

1. Revert the v2.1.0 version.
Release a new MAJOR version (e.g., 3.0.0) that includes the increased minSdkVersion to 21, indicating the breaking change.

2. Mark v2.1.0 as deprecated on pub.dev, to discourage its use in favor of other, more stable versions.

This way, projects with different compatibility requirements can choose the appropriate flutter_mailer version based on their specific needs, effectively resolving the issue.

Please accept my apologies for the confusion caused by my previous message. I deeply appreciate your understanding and assistance in this matter.

Thank you once again for your diligent work on the flutter_mailer package.
