### ISSUE TITLE
Any word on getting this to work on iOS?

### ISSUE THREAD

**Issue by OpticNectar** [taljacobson/flutter_mailer#8]
Is there any word on getting this to work on iOS? Doesn't do anything as of right now.

**Comment by taljacobson** [comment]
Can you provide additional information about the problem?

Note that it only works on a physical device. Since it uses the ios native
mail client which is not present in the simulator.

**Comment by OpticNectar** [comment]
It has to do with my iOS device not having the native Mail app installed. My bad.
